### ISSUE TITLE
[Feature request] Cross-platform support

### ISSUE THREAD

**Issue by Semptra** [Project-KONGOR/Heroes-Of-Newerth-Mod-Manager#19]
Hi, I've noticed that the current version of the program uses Windows Forms as a UI framework. I think it is possible to write a separate version with cross-platform UI framework like [Avalonia](https://avaloniaui.net/). Not sure about the functionality itself (is it cross-platform or windows specific) though.

**Comment by Olindholm** [comment]
I still use the Java version. Works fine.
https://sourceforge.net/projects/all-inhonmodman/

**Comment by Xen0byte** [comment]
> Hi, I've noticed that the current version of the program uses Windows Forms as a UI framework. I think it is possible to write a separate version with cross-platform UI framework like [Avalonia](https://avaloniaui.net/). Not sure about the functionality itself (is it cross-platform or windows specific) though.

There's a PR to upgrade to .NET 6. Once that gets merged, the project will work cross-platform.
